import "./globals.css";

export const metadata = {
  title: "EasyTODO",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh" className="h-full">
      <body className="h-full" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
