import "./globals.css";
import "dayjs/locale/zh-cn";

import Providers from "@/components/Providers";

export const metadata = {
  title: "EasyTODO",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh" className="h-full">
      <body className="h-full overflow-hidden" suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
